### ISSUE TITLE
Epic: Test all the things

### ISSUE THREAD

**Issue by ffMathy** [sponsorkit/sponsorkit.io#22]
- [x] Test for Duplicate Stripe webhook events
- [x] Test for Transaction rollback
- [x] Test for cancellation token (default should be used for Stripe calls)
- [ ] Test React components
- [ ] Test that seeding is not run in production
- [x] Test for input validation (negative amount)
- [x] Test for security issues (ownership)

**Comment by ffMathy** [comment]
Test templates: Started doing Mediatr tests. Just finished SendEmailCommand. About to do EnsureGitHubIssueInDatabaseCommand.

**Comment by ffMathy** [comment]
Finished Mediatr test templates. Later: Do API endpoint tests.

**Comment by ffMathy** [comment]
Reached `src/api/Domain/Controllers/Api/Account/Token/Refresh/Post.cs`, starting from the top. Only templates.

**Comment by ffMathy** [comment]
Test templates done!

**Comment by ffMathy** [comment]
Only 6 tests remain now.

**Comment by ffMathy** [comment]
All tests have finalized, including full flow tests. Will resume with React based tests via a frontend test bridge over at #91. Closing this for now.
