### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ffMathy** [sponsorkit/sponsorkit.io#5]
Roadmap:
- [x] Make test setup work.
- [x] Make signin from Gatsby work, with code/token exchange and private routes.
- [x] Be able to reach a landing page (when signed in), where one can set up beneficiary and/or sponsor profile.
- [x] Be able to create a new bounty.
- [x] Be able to list bounties.
- [x] Be able to view a bounty and add to an existing bounty.
- [ ] Be able to see a list of sponsors.
- [ ] Be able to see a hall of fame for bounty hunters.
- [ ] Finish sponsor payment site.
- [x] Find an icon and a logo. Potential candidate: https://www.iconfinder.com/icons/2264616/bounty_criminal_hunter_military_target_wanted_icon, https://www.iconfinder.com/search/?q=github
- [x] Integrate theme.
- [x] Make Gatsby Cloud work - see https://support.gatsbyjs.com/hc/en-us/articles/360052876613-Using-custom-build-scripts. 
- [ ] Make deploying of API work.
- [x] Setup bountyhunt domain in Joker and point to Cloudflare.
- [x] Work on fees - see #7 also.
- [x] Look at how competitors full flow is. This includes expiration, regretting a bounty, fees etc.
- [x] Set up Amazon KMS for secrets.
- [ ] Test everything locally.
- [ ] Set up integration tests.
